apiVersion: v2
name: secrets-store-csi-driver-provider-aws
version: 1.1.0
kubeVersion: ">=1.17.0-0"
description: A Helm chart for the AWS Secrets Manager and Config Provider for Secret Store CSI Driver
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - "https://github.com/aws/secrets-store-csi-driver-provider-aws"
home: "https://github.com/aws/secrets-store-csi-driver-provider-aws"
type: application
dependencies:
- name: secrets-store-csi-driver
  repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  version: "1.5.0"
  condition: secrets-store-csi-driver.install

keywords:
  - "eks"
  - "secrets-store-csi-driver"
  - "csi"
  - "aws"
  - "secrets manager"
