apiVersion: v2
name: secrets-store-csi-driver-provider-aws
version: 0.3.4
kubeVersion: ">=1.17.0-0"
description: A Helm chart for the AWS Secrets Manager and Config Provider for Secret Store CSI Driver
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - "https://github.com/aws/secrets-store-csi-driver-provider-aws"
home: "https://github.com/aws/secrets-store-csi-driver-provider-aws"
type: application

keywords:
  - "eks"
  - "secrets-store-csi-driver"
  - "csi"
  - "aws"
  - "secrets manager"
